version: '3.8'

services:

  db:
    image: postgres:15
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: blog_db
    ports:
      
      - "5433:5432"


  web:
    build: .
    container_name: blog_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:

      - DATABASE_URL=postgresql+asyncpg://root:rootpassword@db:5432/blog_db